#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-}"
if [[ "$MODE" != "--check-budget" ]]; then
  echo "usage: $0 --check-budget"
  exit 2
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

mkdir -p target/perf docs/perf
LOG_PATH="target/perf/pipeline_latency_snapshot.log"
SUMMARY_JSON="target/perf/pipeline_latency_summary.json"
MATRIX_PATH="target/perf/runtime_allocator_matrix.tsv"
BASELINE_MD="docs/perf/v2_baseline.md"

SNAPSHOT_OUTPUT="$(cargo test -p bench pipeline_latency_snapshot -- --nocapture 2>&1 | tee "$LOG_PATH")"

parse_metric() {
  local key="$1"
  echo "$SNAPSHOT_OUTPUT" | awk -F= -v metric="$key" '$1 ~ metric {print $2}' | tail -1 | tr -d '\r'
}

BATCH_SIZE="$(parse_metric "PIPELINE_BATCH_SIZE")"
ITERATIONS="$(parse_metric "PIPELINE_ITERATIONS")"
P50_US="$(parse_metric "PIPELINE_P50_US")"
P95_US="$(parse_metric "PIPELINE_P95_US")"
P99_US="$(parse_metric "PIPELINE_P99_US")"
AVG_US="$(parse_metric "PIPELINE_AVG_US")"

for value in "$BATCH_SIZE" "$ITERATIONS" "$P50_US" "$P95_US" "$P99_US" "$AVG_US"; do
  if [[ -z "$value" ]]; then
    echo "profile-check: failed to parse benchmark snapshot output"
    exit 1
  fi
done

BUDGET_US="${PIPELINE_P95_BUDGET_US:-2000000}"

cat > "$SUMMARY_JSON" <<JSON
{
  "batch_size": $BATCH_SIZE,
  "iterations": $ITERATIONS,
  "p50_us": $P50_US,
  "p95_us": $P95_US,
  "p99_us": $P99_US,
  "avg_us": $AVG_US,
  "budget_us": $BUDGET_US
}
JSON

cat > "$MATRIX_PATH" <<TSV
runtime	allocator	p95_us	notes
tokio-multi-thread	system	$P95_US	check-budget quick snapshot
TSV

if command -v cargo-flamegraph >/dev/null 2>&1; then
  echo "profile-check: cargo-flamegraph detected (set PROFILE_PIPELINE_FLAMEGRAPH=1 to enable capture)"
  if [[ "${PROFILE_PIPELINE_FLAMEGRAPH:-0}" == "1" ]]; then
    cargo flamegraph -p bench --bench pipeline_latency -o target/perf/pipeline_flamegraph.svg >/dev/null 2>&1 || true
  fi
else
  echo "profile-check: cargo-flamegraph not installed, skipping flamegraph capture"
fi

cat > "$BASELINE_MD" <<MD
# V2 Pipeline Latency Baseline

Generated by \`scripts/profile_pipeline.sh --check-budget\`.

## Snapshot

- Batch size: \`$BATCH_SIZE\`
- Iterations: \`$ITERATIONS\`
- p50: \`$P50_US us\`
- p95: \`$P95_US us\`
- p99: \`$P99_US us\`
- Average: \`$AVG_US us\`
- Budget (p95): \`$BUDGET_US us\`

## Runtime/Allocator Matrix

| Runtime | Allocator | p95 (us) | Notes |
|---|---|---:|---|
| tokio-multi-thread | system | $P95_US | check-budget quick snapshot |

## Artifacts

- \`target/perf/pipeline_latency_summary.json\`
- \`target/perf/runtime_allocator_matrix.tsv\`
- \`target/perf/pipeline_latency_snapshot.log\`
- \`target/perf/pipeline_flamegraph.svg\` (optional, when enabled)
MD

echo "profile-check: p95_us=${P95_US} budget_us=${BUDGET_US}"
if (( P95_US > BUDGET_US )); then
  echo "profile-check: FAIL (p95 exceeds budget)"
  exit 1
fi

echo "profile-check: PASS"
